# Generated by Django 4.2.7 on 2025-12-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Código de Ativação'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='activation_code_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiração do Código'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email Confirmado'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='instituicao_ensino',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instituição de Ensino'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='perfil',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('ORGANIZADOR', 'Organizador')], default='ALUNO', max_length=15, verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
