# Generated by Django 4.2.7 on 2025-12-05 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, help_text='Imagem de divulgação do evento (máx. 5MB, formatos: JPG, PNG, GIF, WebP)', null=True, upload_to='eventos/banners/', validators=[events.models.validate_image_file], verbose_name='Banner do Evento'),
        ),
        migrations.AddField(
            model_name='event',
            name='professor_responsavel',
            field=models.ForeignKey(blank=True, help_text='Professor responsável pelo evento', limit_choices_to={'perfil': 'PROFESSOR'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Professor Responsável'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='presenca_confirmada',
            field=models.BooleanField(default=False, help_text='Indica se o participante teve presença confirmada no evento', verbose_name='Presença Confirmada'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='data_fim',
            field=models.DateField(verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='event',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='event',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='event',
            name='horario_fim',
            field=models.TimeField(verbose_name='Horário de Término'),
        ),
        migrations.AlterField(
            model_name='event',
            name='horario_inicio',
            field=models.TimeField(verbose_name='Horário de Início'),
        ),
        migrations.AlterField(
            model_name='event',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/', validators=[events.models.validate_image_file], verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='event',
            name='local',
            field=models.CharField(max_length=200, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizador',
            field=models.ForeignKey(limit_choices_to={'perfil': 'ORGANIZADOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_organizados', to=settings.AUTH_USER_MODEL, verbose_name='Organizador'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tipo_evento',
            field=models.CharField(choices=[('SEMINARIO', 'Seminário'), ('PALESTRA', 'Palestra'), ('MINICURSO', 'Minicurso'), ('SEMANA_ACADEMICA', 'Semana Acadêmica')], max_length=20, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='event',
            name='vagas',
            field=models.PositiveIntegerField(verbose_name='Quantidade de Vagas'),
        ),
        migrations.AlterField(
            model_name='event',
            name='vagas_disponiveis',
            field=models.PositiveIntegerField(editable=False, verbose_name='Vagas Disponíveis'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='CONFIRMADA', max_length=15, verbose_name='Status'),
        ),
    ]
