# Generated by Django 4.2.7 on 2025-12-05 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_event_banner_event_professor_responsavel_and_more'),
        ('certificates', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='carga_horaria',
            field=models.PositiveIntegerField(verbose_name='Carga Horária'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='codigo_verificacao',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código de Verificação'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='data_emissao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='emitido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='Emitido Por'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='inscricao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificado', to='events.inscription', verbose_name='Inscrição'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
