# Generated by Django 4.2.7 on 2025-12-05 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_CREATED', 'Criação de Usuário'), ('USER_LOGIN', 'Login de Usuário'), ('USER_LOGOUT', 'Logout de Usuário'), ('USER_EMAIL_CONFIRMED', 'Confirmação de Email'), ('EVENT_CREATED', 'Criação de Evento'), ('EVENT_UPDATED', 'Alteração de Evento'), ('EVENT_DELETED', 'Exclusão de Evento'), ('EVENT_API_QUERY', 'Consulta de Evento via API'), ('INSCRIPTION_CREATED', 'Inscrição em Evento'), ('INSCRIPTION_CANCELLED', 'Cancelamento de Inscrição'), ('INSCRIPTION_API', 'Inscrição via API'), ('CERTIFICATE_GENERATED', 'Geração de Certificado'), ('CERTIFICATE_VIEWED', 'Visualização de Certificado'), ('CERTIFICATE_DOWNLOADED', 'Download de Certificado'), ('CERTIFICATE_AUTO_GENERATED', 'Certificado Gerado Automaticamente'), ('PRESENCE_CONFIRMED', 'Presença Confirmada')], max_length=30, verbose_name='Ação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('object_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Objeto')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Objeto')),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Representação do Objeto')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Dados Extras')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'), models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx')],
            },
        ),
    ]
